### ISSUE TITLE
Anki crash whenever I try to add a new card using the addon

### ISSUE THREAD

**Issue by Nada-github** [migaku-official/Migaku-Dictionary-Addon#46]
**Type:**
  - [x] bug
  - [ ] feature
  - [ ] enhancement
  - [ ] question

**Environment:**
  - OS: Windows 10

**I'm going to open a PR to resolve the issue:**
  - [ ] yes
  - [x ] no

**Description:**
[ This is my first time attempting to create cards using Migaku dictionary, after preparing everything in the card whenever I click 'add' to add the card to my deck Anki immediately crashes, a (Not responding) sign appears beside the Migaku card exporter and then I have to restart Anki. 

I hope this is the right place for posting this issue, I will appreciate your help.]

**Comment by KieranBrannigan** [comment]
Thank you for supporting Migaku.

We have closed this issue since this it is >6 months old; if you feel that this issue is still a problem in the latest version, please comment below and we will reopen and begin investigating this issue.

We apologise that recently we didn't have the manpower to maintain these repos properly, but we aim to maintain them better from here on out.

**Comment by SaraSmiseth** [comment]
I still have this problem. Migaku Dictionary Settings say I have version 1.3.8. If I disable the add-on I can add my cards without a problem.

Clicking on Add gives me the following message:

```
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.9.6 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2021-08-10 10:49:46

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
  File "/usr/lib/python3.9/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
  File "/usr/lib/python3.9/inspect.py", line 3062, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.9/inspect.py", line 2983, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

**Comment by Cephian** [comment]
I am getting the exact same error as SaraSmiseth with identical debug info. Commenting out the line
> AddCards.addCards = wrap(AddCards.addCards, addEditActivated)

in main.py will get rid of the error on adding. I'm not familiar enough with the Migaku Dictionary codebase to know what addEditActivated is actually doing here, but commenting this out doesn't seem to interfere with any functionality I currently use.  According to the AnkiWeb page an extension upgrade is beginning soon (Sept 16 2021) so it might be best to wait until after that and see if this issue persists.

**Comment by mainrs** [comment]
It actually persists. @Cephian does the new update work on your side?

**Comment by Cephian** [comment]
I stopped using Migaku tools in favor of [mpvacious](https://github.com/Ajatt-Tools/mpvacious) so I don't have access to whatever updates been posted on Patreon. I see the Ankiweb version has not been updated since my last comment. I'd be happy to test it out whatever releases I have access to even though if I don't plan on using them personally.
